<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-J833GHP" failures="1" tests="6" name="test" time="0.141" errors="0" timestamp="2022-01-06T15:46:37 CET">
  <testcase classname="test.Classtest1" name="Demo" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Classtest1.Demo(Classtest1.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Classtest2" name="LoginAPIcarLoan" time="0.003"/>
  <testcase classname="test.Classtest2" name="WebloginCarLoan" time="0.005"/>
  <testcase classname="test.Classtest4" name="LoginAPIcarLoan" time="0.004"/>
  <testcase classname="test.Classtest4" name="MobileLiginCarLoan" time="0.001"/>
  <testcase classname="test.Classtest4" name="WebloginCarLoan" time="0.001"/>
  <testcase classname="test.Classtest1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- test -->
